use_frameworks!

platform :ios, '8.0'

target 'LMDeviceInfoCollector_Example' do
  pod 'LMDeviceInfoCollector', :path => '../'

  target 'LMDeviceInfoCollector_Tests' do
    inherit! :search_paths

    
  end
end
